### PR TITLE
Feature way back machine

### PR DESCRIPTION
**Pull request by badalsarkar**
Hi,
I have implemented the feature: searching in wayback machine. I have also updated the Readme file.

Thanks for considering this.
Badal

### CODE REVIEW

**Comment by VietnameZe** [comment]
Hi bro, when I run command ```insane-cli -w https://finance.yahoo.com 2016```, I get 'command not found'.  Be aware that the 'timestamp' 2016 is supposed to be at arg[5], arg[4] is url you passed on.

**Comment by VietnameZe** [comment]
full command should have been `node insane-cli xxx yyy zzz` (with node at beginning). So just a problem with args order

**Comment by badalsarkar** [comment]
> full command should have been `node insane-cli xxx yyy zzz` (with node at beginning). So just a problem with args order

Yes. I just made it consistent with your readme. Is it working now?

**Comment by VietnameZe** [comment]
I think you should make another pull request or update the previous one

**Comment by badalsarkar** [comment]
> I think you should make another pull request or update the previous one

Sure. You mean to update the readme file? Or any modification needed in the code?

**Comment by VietnameZe** [comment]
yeah in the code, readme file seem okay, but the code when I run ```insane-cli -w https://finance.yahoo.com 2016``` I get "command not found" error.

**Comment by VietnameZe** [comment]
actually it was my bad, I hadn't switched to your branch so the code didn't work, now ok, you don't have to make any change

**Pull request merged**
